/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedReflectionRouteImport } from './routes/_authenticated/reflection'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedActionActionIdRouteImport } from './routes/_authenticated/action/$actionId'
import { Route as AuthenticatedNewIndexRouteImport } from './routes/_authenticated/new/index'
import { Route as AuthenticatedNewTypeRouteImport } from './routes/_authenticated/new/$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReflectionRoute = AuthenticatedReflectionRouteImport.update({
  id: '/reflection',
  path: '/reflection',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActionActionIdRoute =
  AuthenticatedActionActionIdRouteImport.update({
    id: '/action/$actionId',
    path: '/action/$actionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewIndexRoute = AuthenticatedNewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewTypeRoute = AuthenticatedNewTypeRouteImport.update({
  id: '/new/$type',
  path: '/new/$type',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/reflection': typeof AuthenticatedReflectionRoute
  '/today': typeof AuthenticatedTodayRoute
  '/action/$actionId': typeof AuthenticatedActionActionIdRoute
  '/new/$type': typeof AuthenticatedNewTypeRoute
  '/new/': typeof AuthenticatedNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/reflection': typeof AuthenticatedReflectionRoute
  '/today': typeof AuthenticatedTodayRoute
  '/action/$actionId': typeof AuthenticatedActionActionIdRoute
  '/new/$type': typeof AuthenticatedNewTypeRoute
  '/new': typeof AuthenticatedNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/reflection': typeof AuthenticatedReflectionRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/action/$actionId': typeof AuthenticatedActionActionIdRoute
  '/_authenticated/new/$type': typeof AuthenticatedNewTypeRoute
  '/_authenticated/new/': typeof AuthenticatedNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/goals'
    | '/reflection'
    | '/today'
    | '/action/$actionId'
    | '/new/$type'
    | '/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/goals'
    | '/reflection'
    | '/today'
    | '/action/$actionId'
    | '/new/$type'
    | '/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/goals'
    | '/_authenticated/reflection'
    | '/_authenticated/today'
    | '/_authenticated/action/$actionId'
    | '/_authenticated/new/$type'
    | '/_authenticated/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reflection': {
      id: '/_authenticated/reflection'
      path: '/reflection'
      fullPath: '/reflection'
      preLoaderRoute: typeof AuthenticatedReflectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/action/$actionId': {
      id: '/_authenticated/action/$actionId'
      path: '/action/$actionId'
      fullPath: '/action/$actionId'
      preLoaderRoute: typeof AuthenticatedActionActionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new/': {
      id: '/_authenticated/new/'
      path: '/new'
      fullPath: '/new/'
      preLoaderRoute: typeof AuthenticatedNewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new/$type': {
      id: '/_authenticated/new/$type'
      path: '/new/$type'
      fullPath: '/new/$type'
      preLoaderRoute: typeof AuthenticatedNewTypeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedReflectionRoute: typeof AuthenticatedReflectionRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedActionActionIdRoute: typeof AuthenticatedActionActionIdRoute
  AuthenticatedNewTypeRoute: typeof AuthenticatedNewTypeRoute
  AuthenticatedNewIndexRoute: typeof AuthenticatedNewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedReflectionRoute: AuthenticatedReflectionRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedActionActionIdRoute: AuthenticatedActionActionIdRoute,
  AuthenticatedNewTypeRoute: AuthenticatedNewTypeRoute,
  AuthenticatedNewIndexRoute: AuthenticatedNewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
