/**
 * Единый набор иконок приложения. Имена сохраняют совместимость с текущими
 * компонентами, а сами SVG берутся из Phosphor Regular.
 */
export {
  Archive,
  Bell,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut as OpenNewWindow,
  ArrowUUpLeft as Undo,
  ArrowsClockwise as RefreshDouble,
  Calendar,
  CalendarPlus,
  CaretDown as NavArrowDown,
  CaretLeft as NavArrowLeft,
  CaretRight as NavArrowRight,
  CaretUp as NavArrowUp,
  Check,
  CheckSquare,
  Circle,
  Clock,
  CloudSun as CloudSunny,
  DotsSixVertical as DotsGrid3x3,
  DotsThree as MoreHoriz,
  DotsThreeVertical as MoreVert,
  Hourglass,
  House as HomeSimple,
  ListChecks as TaskList,
  MagnifyingGlass as Search,
  Minus,
  Moon as HalfMoon,
  Newspaper as JournalPage,
  PencilSimple as EditPencil,
  Plus,
  Repeat,
  SidebarSimple as SidebarCollapse,
  SkipForward as SkipNext,
  Sparkle as CircleSpark,
  Sparkle as Sparks,
  Sun as SunLight,
  Trash,
  Trophy,
  X as Xmark,
} from "@phosphor-icons/react";
